// 瞬間英作文 5日間プログラム データ（康平さん苦手文法 強化版）
// 各文に day (1〜5) を付与。ある日のセットは day <= その日番号 のすべての文。
// 対象文法: 仮定法・条件文 / 関係代名詞 / 受動態 / 現在完了・過去完了 を均等配分（各25問、計100問）。
// 1日20問ずつ新規追加、前日までの問題を必ず含む累積構成。すべて接続詞・関係詞でつないだ複文。

const ALL_SENTENCES = [
  // ===== Day 1 (新規20問) =====
  {day:1, grammar:"conditional", jp:"もし彼に会ったら、これを渡してください。", en:"If you see him, please give this to him."},
  {day:1, grammar:"conditional", jp:"お金があれば、新しい車を買うのに。", en:"If I had money, I would buy a new car."},
  {day:1, grammar:"conditional", jp:"もっと早く出発していたら、電車に間に合っていただろう。", en:"If we had left earlier, we would have caught the train."},
  {day:1, grammar:"conditional", jp:"明日雨が降らなければ、ピクニックに行こう。", en:"If it doesn't rain tomorrow, let's go on a picnic."},
  {day:1, grammar:"conditional", jp:"彼が謝らない限り、私は許さない。", en:"Unless he apologizes, I won't forgive him."},
  {day:1, grammar:"relative", jp:"あそこに立っている男性は私の先生だ。", en:"The man who is standing over there is my teacher."},
  {day:1, grammar:"relative", jp:"これは私が去年買った本だ。", en:"This is the book I bought last year."},
  {day:1, grammar:"relative", jp:"昨日会った女性はとても親切だった。", en:"The woman I met yesterday was very kind."},
  {day:1, grammar:"relative", jp:"これは彼が作ったケーキだ。", en:"This is the cake he made."},
  {day:1, grammar:"relative", jp:"東京に住んでいる友達がいる。", en:"I have a friend who lives in Tokyo."},
  {day:1, grammar:"passive", jp:"雨が降っていたので、その試合は中止された。", en:"Because it was raining, the game was canceled."},
  {day:1, grammar:"passive", jp:"彼が指示を出すまで、何も決められなかった。", en:"Nothing could be decided until he gave instructions."},
  {day:1, grammar:"passive", jp:"その本は多くの人に読まれているので、有名になった。", en:"Because that book is read by many people, it has become famous."},
  {day:1, grammar:"passive", jp:"火事が起きたとき、その建物はすでに建てられていた。", en:"When the fire broke out, the building had already been built."},
  {day:1, grammar:"passive", jp:"予算が足りなかったので、その計画は中止された。", en:"Because there wasn't enough budget, the plan was canceled."},
  {day:1, grammar:"perfect", jp:"ここに引っ越してから、私は多くの友達を作った。", en:"Since I moved here, I have made many friends."},
  {day:1, grammar:"perfect", jp:"彼女はまだ来ていないので、私たちは会議を始められない。", en:"Because she hasn't arrived yet, we can't start the meeting."},
  {day:1, grammar:"perfect", jp:"家に着いたとき、雨はもうやんでいた。", en:"When I got home, the rain had already stopped."},
  {day:1, grammar:"perfect", jp:"彼が到着する前に、私たちはすでに出発していた。", en:"We had already left before he arrived."},
  {day:1, grammar:"perfect", jp:"その映画が始まる前に、彼はすでに寝ていた。", en:"He had already fallen asleep before the movie started."},

  // ===== Day 2 (新規20問) =====
  {day:2, grammar:"conditional", jp:"何か困ったことがあれば、いつでも連絡してください。", en:"If you have any trouble, please contact me anytime."},
  {day:2, grammar:"conditional", jp:"もし彼女がここにいたら、驚くだろう。", en:"If she were here, she would be surprised."},
  {day:2, grammar:"conditional", jp:"もっと注意していたら、そのミスは防げただろう。", en:"If I had been more careful, I could have prevented that mistake."},
  {day:2, grammar:"conditional", jp:"万が一遅れる場合は、電話してください。", en:"In case you are late, please call me."},
  {day:2, grammar:"conditional", jp:"十分練習しさえすれば、誰でも上手になれる。", en:"As long as you practice enough, anyone can improve."},
  {day:2, grammar:"relative", jp:"これは私の父が建てた家です。", en:"This is the house that my father built."},
  {day:2, grammar:"relative", jp:"英語を話せる人を探しています。", en:"I'm looking for someone who can speak English."},
  {day:2, grammar:"relative", jp:"彼が読んでいる本はとても分厚い。", en:"The book he is reading is very thick."},
  {day:2, grammar:"relative", jp:"昨夜私に電話をくれた人は誰ですか。", en:"Who is the person who called me last night?"},
  {day:2, grammar:"relative", jp:"これは去年私たちが訪れた町だ。", en:"This is the town we visited last year."},
  {day:2, grammar:"passive", jp:"彼が謝るまで、その問題は解決されなかった。", en:"The problem wasn't solved until he apologized."},
  {day:2, grammar:"passive", jp:"締め切りが近づいていたので、その報告書は急いで書かれた。", en:"Because the deadline was approaching, the report was written in a hurry."},
  {day:2, grammar:"passive", jp:"全員が到着してから、会議は始められた。", en:"The meeting was started after everyone had arrived."},
  {day:2, grammar:"passive", jp:"事故が起きたので、その道路は閉鎖された。", en:"Because an accident happened, the road was closed."},
  {day:2, grammar:"passive", jp:"雪が降り続いたので、多くの便が欠航にされた。", en:"Because it kept snowing, many flights were canceled."},
  {day:2, grammar:"perfect", jp:"彼女に会うまで、私は彼女の名前を聞いたことがなかった。", en:"I had never heard her name until I met her."},
  {day:2, grammar:"perfect", jp:"彼が来た時には、パーティーはすでに終わっていた。", en:"By the time he came, the party had already ended."},
  {day:2, grammar:"perfect", jp:"3年間ここで働いているので、仕事に慣れた。", en:"Since I have worked here for three years, I've gotten used to the job."},
  {day:2, grammar:"perfect", jp:"彼女が起きたとき、朝食はすでに作られていた。", en:"When she woke up, breakfast had already been made."},
  {day:2, grammar:"perfect", jp:"英語を10年間勉強しているので、彼はかなり上手に話せる。", en:"Since he has studied English for ten years, he can speak it quite well."},

  // ===== Day 3 (新規20問) =====
  {day:3, grammar:"conditional", jp:"一度試してみれば、きっと好きになるよ。", en:"Once you try it, you will surely like it."},
  {day:3, grammar:"conditional", jp:"たとえ雨が降っても、私たちは出発します。", en:"Even if it rains, we will leave."},
  {day:3, grammar:"conditional", jp:"もし彼がもっと早く教えてくれていたら、私は準備できていた。", en:"If he had told me earlier, I would have been prepared."},
  {day:3, grammar:"conditional", jp:"もし今日が休みだったら、旅行に行くのに。", en:"If today were a holiday, I would go on a trip."},
  {day:3, grammar:"conditional", jp:"彼が来なければ、私たちだけで始めよう。", en:"If he doesn't come, let's start without him."},
  {day:3, grammar:"relative", jp:"私が尊敬している先生はもう退職した。", en:"The teacher I respect has already retired."},
  {day:3, grammar:"relative", jp:"彼女が住んでいる家はとても大きい。", en:"The house she lives in is very big."},
  {day:3, grammar:"relative", jp:"これは私が今まで読んだ中で一番面白い本だ。", en:"This is the most interesting book I have ever read."},
  {day:3, grammar:"relative", jp:"隣に座っている女性は私の姉です。", en:"The woman sitting next to me is my sister."},
  {day:3, grammar:"relative", jp:"彼が働いている会社は有名だ。", en:"The company he works for is famous."},
  {day:3, grammar:"passive", jp:"新しい工場が建てられてから、生産量が増えた。", en:"Since the new factory was built, production has increased."},
  {day:3, grammar:"passive", jp:"その歌は世界中で歌われているので、誰でも知っている。", en:"Because that song is sung all over the world, everyone knows it."},
  {day:3, grammar:"passive", jp:"材料が集められると、すぐに料理が作られた。", en:"As soon as the ingredients were gathered, the dish was made."},
  {day:3, grammar:"passive", jp:"規則が変更されたので、私たちは従わなければならない。", en:"Because the rules were changed, we have to follow them."},
  {day:3, grammar:"passive", jp:"彼が到着する前に、部屋はきれいに掃除されていた。", en:"The room had already been cleaned before he arrived."},
  {day:3, grammar:"perfect", jp:"私たちがそこに着いたとき、コンサートはすでに始まっていた。", en:"When we arrived there, the concert had already started."},
  {day:3, grammar:"perfect", jp:"彼が電話をくれるまで、私は何も知らなかった。", en:"I hadn't known anything until he called me."},
  {day:3, grammar:"perfect", jp:"彼女は結婚してから、ずっと大阪に住んでいる。", en:"Since she got married, she has been living in Osaka."},
  {day:3, grammar:"perfect", jp:"私が空港に着く前に、飛行機はすでに出発していた。", en:"The plane had already departed before I got to the airport."},
  {day:3, grammar:"perfect", jp:"彼はその映画を三回見たことがあるので、内容をよく知っている。", en:"Because he has seen that movie three times, he knows the story well."},

  // ===== Day 4 (新規20問) =====
  {day:4, grammar:"conditional", jp:"もし彼が本当のことを話していたら、問題は起きなかっただろう。", en:"If he had told the truth, the problem wouldn't have happened."},
  {day:4, grammar:"conditional", jp:"あなたがもっと早く起きれば、遅刻しないだろう。", en:"If you get up earlier, you won't be late."},
  {day:4, grammar:"conditional", jp:"十分な情報がなければ、正しい決断はできない。", en:"If we don't have enough information, we can't make the right decision."},
  {day:4, grammar:"conditional", jp:"たとえ彼が反対しても、私は計画を進めるつもりだ。", en:"Even if he objects, I will go ahead with the plan."},
  {day:4, grammar:"conditional", jp:"電車に乗り遅れたら、タクシーを使おう。", en:"If we miss the train, let's take a taxi."},
  {day:4, grammar:"relative", jp:"これは彼女がくれたプレゼントだ。", en:"This is the present she gave me."},
  {day:4, grammar:"relative", jp:"その計画を立てた人は誰ですか。", en:"Who is the person that made that plan?"},
  {day:4, grammar:"relative", jp:"私たちが泊まったホテルは駅の近くにあった。", en:"The hotel we stayed at was near the station."},
  {day:4, grammar:"relative", jp:"彼が話していることは本当だ。", en:"What he is saying is true."},
  {day:4, grammar:"relative", jp:"これは私が探していた鍵だ。", en:"This is the key I was looking for."},
  {day:4, grammar:"passive", jp:"予約がキャンセルされたので、席が空いた。", en:"Because the reservation was canceled, a seat became available."},
  {day:4, grammar:"passive", jp:"犯人が捕まるまで、街は不安に包まれていた。", en:"The town was filled with anxiety until the criminal was caught."},
  {day:4, grammar:"passive", jp:"契約が結ばれると、プロジェクトはすぐに開始された。", en:"As soon as the contract was signed, the project was started."},
  {day:4, grammar:"passive", jp:"資金が集められたので、その施設は建設された。", en:"Because funds were collected, the facility was built."},
  {day:4, grammar:"passive", jp:"台風が接近していたので、イベントは延期された。", en:"Because a typhoon was approaching, the event was postponed."},
  {day:4, grammar:"perfect", jp:"私たちが到着したとき、彼はすでに準備を終えていた。", en:"When we arrived, he had already finished getting ready."},
  {day:4, grammar:"perfect", jp:"彼女がここに来てから、状況はずいぶん変わった。", en:"Since she came here, the situation has changed a lot."},
  {day:4, grammar:"perfect", jp:"彼が謝る前に、彼女はすでに彼を許していた。", en:"She had already forgiven him before he apologized."},
  {day:4, grammar:"perfect", jp:"何年も会っていないので、彼の顔を忘れてしまった。", en:"Because I haven't seen him for years, I've forgotten his face."},
  {day:4, grammar:"perfect", jp:"私が起きたときには、家族はすでに朝食を食べ終えていた。", en:"When I woke up, my family had already finished breakfast."},

  // ===== Day 5 (新規20問) =====
  {day:5, grammar:"conditional", jp:"もし宝くじが当たったら、何をしますか。", en:"If you won the lottery, what would you do?"},
  {day:5, grammar:"conditional", jp:"早く準備しておけば、慌てずに済んだのに。", en:"If we had prepared early, we wouldn't have had to rush."},
  {day:5, grammar:"conditional", jp:"何か質問があれば、遠慮なく聞いてください。", en:"If you have any questions, feel free to ask."},
  {day:5, grammar:"conditional", jp:"もし彼を知っていたら、紹介してほしい。", en:"If you know him, I want you to introduce him to me."},
  {day:5, grammar:"conditional", jp:"急がなければ、開演に間に合わないだろう。", en:"If we don't hurry, we won't make it in time for the show."},
  {day:5, grammar:"relative", jp:"その事故を目撃した人は警察に連絡した。", en:"The person who witnessed the accident called the police."},
  {day:5, grammar:"relative", jp:"彼が信頼している唯一の人は彼の母親だ。", en:"The only person he trusts is his mother."},
  {day:5, grammar:"relative", jp:"これは私が生まれた町だ。", en:"This is the town where I was born."},
  {day:5, grammar:"relative", jp:"明日会う予定の人はとても有名な医者だ。", en:"The person I'm meeting tomorrow is a very famous doctor."},
  {day:5, grammar:"relative", jp:"それが彼が仕事を辞めた理由だ。", en:"That is the reason why he quit his job."},
  {day:5, grammar:"passive", jp:"彼が説明してくれたので、その仕組みはよく理解された。", en:"Because he explained it, the system was well understood."},
  {day:5, grammar:"passive", jp:"その絵は有名な画家によって描かれたので、高く売れた。", en:"Because that painting was drawn by a famous artist, it sold for a high price."},
  {day:5, grammar:"passive", jp:"十分な証拠が集まるまで、彼は逮捕されなかった。", en:"He wasn't arrested until enough evidence was gathered."},
  {day:5, grammar:"passive", jp:"電気が復旧してから、工場は再び稼働された。", en:"The factory was operated again after the power was restored."},
  {day:5, grammar:"passive", jp:"招待状が送られると、多くの人が集まった。", en:"As soon as the invitations were sent, many people gathered."},
  {day:5, grammar:"perfect", jp:"彼女がそのニュースを聞くまで、誰も真実を知らなかった。", en:"No one had known the truth until she heard the news."},
  {day:5, grammar:"perfect", jp:"何度も練習してきたので、彼は本番でも緊張しなかった。", en:"Because he had practiced many times, he wasn't nervous during the actual performance."},
  {day:5, grammar:"perfect", jp:"彼が到着する頃には、私たちは仕事を終えていた。", en:"By the time he arrived, we had finished the work."},
  {day:5, grammar:"perfect", jp:"その本を読んでからずっと、彼女はその作家のファンだ。", en:"She has been a fan of that author ever since she read the book."},
  {day:5, grammar:"perfect", jp:"会議が始まる前に、資料はすでに配られていた。", en:"The materials had already been handed out before the meeting started."}
];
